// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetReq struct {
	Space                string   `protobuf:"bytes,1,opt,name=Space,proto3" json:"Space,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResp struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (m *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(m, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DelReq struct {
	Space                string   `protobuf:"bytes,1,opt,name=Space,proto3" json:"Space,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (m *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(m, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *DelReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResp) Reset()         { *m = DelResp{} }
func (m *DelResp) String() string { return proto.CompactTextString(m) }
func (*DelResp) ProtoMessage()    {}
func (*DelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *DelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResp.Unmarshal(m, b)
}
func (m *DelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResp.Marshal(b, m, deterministic)
}
func (m *DelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResp.Merge(m, src)
}
func (m *DelResp) XXX_Size() int {
	return xxx_messageInfo_DelResp.Size(m)
}
func (m *DelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelResp proto.InternalMessageInfo

type RefreshReq struct {
	Space                string   `protobuf:"bytes,1,opt,name=Space,proto3" json:"Space,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshReq) Reset()         { *m = RefreshReq{} }
func (m *RefreshReq) String() string { return proto.CompactTextString(m) }
func (*RefreshReq) ProtoMessage()    {}
func (*RefreshReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *RefreshReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshReq.Unmarshal(m, b)
}
func (m *RefreshReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshReq.Marshal(b, m, deterministic)
}
func (m *RefreshReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshReq.Merge(m, src)
}
func (m *RefreshReq) XXX_Size() int {
	return xxx_messageInfo_RefreshReq.Size(m)
}
func (m *RefreshReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshReq proto.InternalMessageInfo

func (m *RefreshReq) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *RefreshReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RefreshResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResp) Reset()         { *m = RefreshResp{} }
func (m *RefreshResp) String() string { return proto.CompactTextString(m) }
func (*RefreshResp) ProtoMessage()    {}
func (*RefreshResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *RefreshResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResp.Unmarshal(m, b)
}
func (m *RefreshResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResp.Marshal(b, m, deterministic)
}
func (m *RefreshResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResp.Merge(m, src)
}
func (m *RefreshResp) XXX_Size() int {
	return xxx_messageInfo_RefreshResp.Size(m)
}
func (m *RefreshResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetReq)(nil), "GetReq")
	proto.RegisterType((*GetResp)(nil), "GetResp")
	proto.RegisterType((*DelReq)(nil), "DelReq")
	proto.RegisterType((*DelResp)(nil), "DelResp")
	proto.RegisterType((*RefreshReq)(nil), "RefreshReq")
	proto.RegisterType((*RefreshResp)(nil), "RefreshResp")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0xca, 0x82, 0x40,
	0x14, 0x40, 0xf1, 0xf3, 0xcb, 0xd1, 0xab, 0x41, 0x5c, 0x5a, 0x0c, 0x42, 0x10, 0xd2, 0xa2, 0xd5,
	0x10, 0xd5, 0x13, 0x94, 0xe0, 0xa2, 0xdd, 0xf8, 0x04, 0x2a, 0x57, 0x0a, 0x04, 0x27, 0x67, 0x08,
	0x7a, 0xfb, 0x70, 0xb4, 0x9f, 0xad, 0xbb, 0x3b, 0x03, 0xe7, 0xcc, 0x99, 0x0b, 0xbe, 0x2a, 0x85,
	0xea, 0x5a, 0xd3, 0x26, 0x3b, 0xf0, 0x32, 0x32, 0x92, 0xee, 0xb8, 0x84, 0x59, 0xae, 0x8a, 0x8a,
	0xb8, 0xb3, 0x76, 0xb6, 0x81, 0x1c, 0x0e, 0xb8, 0x00, 0xf7, 0x42, 0x4f, 0xfe, 0x67, 0xef, 0xfa,
	0x31, 0x59, 0x01, 0xb3, 0x84, 0x56, 0x88, 0xf0, 0x9f, 0x16, 0xa6, 0xb0, 0x44, 0x24, 0xed, 0xdc,
	0x0b, 0x53, 0x6a, 0xa6, 0x08, 0x03, 0x60, 0x96, 0xd0, 0x2a, 0x39, 0x02, 0x48, 0xaa, 0x3b, 0xd2,
	0xd7, 0x29, 0x82, 0x39, 0x84, 0x1f, 0x4a, 0xab, 0x7d, 0x0d, 0x20, 0xcf, 0xa7, 0x9c, 0xba, 0xc7,
	0xad, 0x22, 0xe4, 0xe0, 0x66, 0x64, 0x90, 0x89, 0xe1, 0x9b, 0xb1, 0x2f, 0xde, 0xf5, 0x1c, 0xdc,
	0x94, 0x1a, 0x64, 0x62, 0xe8, 0x8d, 0x7d, 0x31, 0x66, 0xe0, 0x06, 0xd8, 0x28, 0xc4, 0x50, 0x7c,
	0x83, 0xe2, 0x48, 0xfc, 0xbc, 0x53, 0x7a, 0x76, 0x83, 0x87, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xaf, 0x05, 0x99, 0x2c, 0x4d, 0x01, 0x00, 0x00,
}
